// <auto-generated />
namespace BMA.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initializeDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initializeDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201302212215268_initializeDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
