//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMain")]
    public interface IMain {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllTransactions", ReplyAction="http://tempuri.org/IMain/GetAllTransactionsResponse")]
        System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction> GetAllTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllTransactions", ReplyAction="http://tempuri.org/IMain/GetAllTransactionsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction>> GetAllTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllBudgets", ReplyAction="http://tempuri.org/IMain/GetAllBudgetsResponse")]
        System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Budget> GetAllBudgets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllBudgets", ReplyAction="http://tempuri.org/IMain/GetAllBudgetsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Budget>> GetAllBudgetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllTransCategories", ReplyAction="http://tempuri.org/IMain/GetAllTransCategoriesResponse")]
        System.Collections.Generic.Dictionary<BMA.BusinessLogic.Category, System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction>> GetAllTransCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllTransCategories", ReplyAction="http://tempuri.org/IMain/GetAllTransCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<BMA.BusinessLogic.Category, System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction>>> GetAllTransCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllTypeTransactions", ReplyAction="http://tempuri.org/IMain/GetAllTypeTransactionsResponse")]
        System.Collections.ObjectModel.Collection<BMA.BusinessLogic.TypeTransaction> GetAllTypeTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllTypeTransactions", ReplyAction="http://tempuri.org/IMain/GetAllTypeTransactionsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<BMA.BusinessLogic.TypeTransaction>> GetAllTypeTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/LoadItemCounts", ReplyAction="http://tempuri.org/IMain/LoadItemCountsResponse")]
        BMA.BusinessLogic.StartupInfo LoadItemCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/LoadItemCounts", ReplyAction="http://tempuri.org/IMain/LoadItemCountsResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.StartupInfo> LoadItemCountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllStaticData", ReplyAction="http://tempuri.org/IMain/GetAllStaticDataResponse")]
        BMA.BusinessLogic.StaticTypeList GetAllStaticData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/GetAllStaticData", ReplyAction="http://tempuri.org/IMain/GetAllStaticDataResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.StaticTypeList> GetAllStaticDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainChannel : ConsoleApplication1.ServiceReference1.IMain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IMain>, ConsoleApplication1.ServiceReference1.IMain {
        
        public MainClient() {
        }
        
        public MainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction> GetAllTransactions() {
            return base.Channel.GetAllTransactions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction>> GetAllTransactionsAsync() {
            return base.Channel.GetAllTransactionsAsync();
        }
        
        public System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Budget> GetAllBudgets() {
            return base.Channel.GetAllBudgets();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Budget>> GetAllBudgetsAsync() {
            return base.Channel.GetAllBudgetsAsync();
        }
        
        public System.Collections.Generic.Dictionary<BMA.BusinessLogic.Category, System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction>> GetAllTransCategories() {
            return base.Channel.GetAllTransCategories();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<BMA.BusinessLogic.Category, System.Collections.ObjectModel.Collection<BMA.BusinessLogic.Transaction>>> GetAllTransCategoriesAsync() {
            return base.Channel.GetAllTransCategoriesAsync();
        }
        
        public System.Collections.ObjectModel.Collection<BMA.BusinessLogic.TypeTransaction> GetAllTypeTransactions() {
            return base.Channel.GetAllTypeTransactions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<BMA.BusinessLogic.TypeTransaction>> GetAllTypeTransactionsAsync() {
            return base.Channel.GetAllTypeTransactionsAsync();
        }
        
        public BMA.BusinessLogic.StartupInfo LoadItemCounts() {
            return base.Channel.LoadItemCounts();
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.StartupInfo> LoadItemCountsAsync() {
            return base.Channel.LoadItemCountsAsync();
        }
        
        public BMA.BusinessLogic.StaticTypeList GetAllStaticData() {
            return base.Channel.GetAllStaticData();
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.StaticTypeList> GetAllStaticDataAsync() {
            return base.Channel.GetAllStaticDataAsync();
        }
    }
}
