//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IStatic")]
    public interface IStatic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/AuthenticateUser", ReplyAction="http://tempuri.org/IStatic/AuthenticateUserResponse")]
        BMA.BusinessLogic.User AuthenticateUser(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/AuthenticateUser", ReplyAction="http://tempuri.org/IStatic/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.User> AuthenticateUserAsync(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/RegisterUser", ReplyAction="http://tempuri.org/IStatic/RegisterUserResponse")]
        BMA.BusinessLogic.User RegisterUser(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/RegisterUser", ReplyAction="http://tempuri.org/IStatic/RegisterUserResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.User> RegisterUserAsync(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/ChangePassword", ReplyAction="http://tempuri.org/IStatic/ChangePasswordResponse")]
        BMA.BusinessLogic.User ChangePassword(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/ChangePassword", ReplyAction="http://tempuri.org/IStatic/ChangePasswordResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.User> ChangePasswordAsync(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/ForgotPassword", ReplyAction="http://tempuri.org/IStatic/ForgotPasswordResponse")]
        BMA.BusinessLogic.User ForgotPassword(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/ForgotPassword", ReplyAction="http://tempuri.org/IStatic/ForgotPasswordResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.User> ForgotPasswordAsync(BMA.BusinessLogic.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllStaticData", ReplyAction="http://tempuri.org/IStatic/GetAllStaticDataResponse")]
        BMA.BusinessLogic.StaticTypeList GetAllStaticData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllStaticData", ReplyAction="http://tempuri.org/IStatic/GetAllStaticDataResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.StaticTypeList> GetAllStaticDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllCategories", ReplyAction="http://tempuri.org/IStatic/GetAllCategoriesResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.Category> GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllCategories", ReplyAction="http://tempuri.org/IStatic/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Category>> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllTypeTransactionReasons", ReplyAction="http://tempuri.org/IStatic/GetAllTypeTransactionReasonsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> GetAllTypeTransactionReasons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllTypeTransactionReasons", ReplyAction="http://tempuri.org/IStatic/GetAllTypeTransactionReasonsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason>> GetAllTypeTransactionReasonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllTypeTransactions", ReplyAction="http://tempuri.org/IStatic/GetAllTypeTransactionsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> GetAllTypeTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetAllTypeTransactions", ReplyAction="http://tempuri.org/IStatic/GetAllTypeTransactionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction>> GetAllTypeTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetUpcomingNotifications", ReplyAction="http://tempuri.org/IStatic/GetUpcomingNotificationsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.Notification> GetUpcomingNotifications(System.DateTime clientTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/GetUpcomingNotifications", ReplyAction="http://tempuri.org/IStatic/GetUpcomingNotificationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Notification>> GetUpcomingNotificationsAsync(System.DateTime clientTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncStaticData", ReplyAction="http://tempuri.org/IStatic/SyncStaticDataResponse")]
        BMA.BusinessLogic.StaticTypeList SyncStaticData(BMA.BusinessLogic.StaticTypeList staticData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncStaticData", ReplyAction="http://tempuri.org/IStatic/SyncStaticDataResponse")]
        System.Threading.Tasks.Task<BMA.BusinessLogic.StaticTypeList> SyncStaticDataAsync(BMA.BusinessLogic.StaticTypeList staticData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncCategories", ReplyAction="http://tempuri.org/IStatic/SyncCategoriesResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.Category> SyncCategories(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncCategories", ReplyAction="http://tempuri.org/IStatic/SyncCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Category>> SyncCategoriesAsync(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeTransactionReasons", ReplyAction="http://tempuri.org/IStatic/SyncTypeTransactionReasonsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> SyncTypeTransactionReasons(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeTransactionReasons", ReplyAction="http://tempuri.org/IStatic/SyncTypeTransactionReasonsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason>> SyncTypeTransactionReasonsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncNotifications", ReplyAction="http://tempuri.org/IStatic/SyncNotificationsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.Notification> SyncNotifications(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncNotifications", ReplyAction="http://tempuri.org/IStatic/SyncNotificationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Notification>> SyncNotificationsAsync(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeTransactions", ReplyAction="http://tempuri.org/IStatic/SyncTypeTransactionsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> SyncTypeTransactions(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeTransactions", ReplyAction="http://tempuri.org/IStatic/SyncTypeTransactionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction>> SyncTypeTransactionsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeFrequencies", ReplyAction="http://tempuri.org/IStatic/SyncTypeFrequenciesResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> SyncTypeFrequencies(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeFrequencies", ReplyAction="http://tempuri.org/IStatic/SyncTypeFrequenciesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency>> SyncTypeFrequenciesAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeIntervals", ReplyAction="http://tempuri.org/IStatic/SyncTypeIntervalsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> SyncTypeIntervals(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncTypeIntervals", ReplyAction="http://tempuri.org/IStatic/SyncTypeIntervalsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval>> SyncTypeIntervalsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncBudgetThresholds", ReplyAction="http://tempuri.org/IStatic/SyncBudgetThresholdsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> SyncBudgetThresholds(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SyncBudgetThresholds", ReplyAction="http://tempuri.org/IStatic/SyncBudgetThresholdsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold>> SyncBudgetThresholdsAsync(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveCategories", ReplyAction="http://tempuri.org/IStatic/SaveCategoriesResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.Category> SaveCategories(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveCategories", ReplyAction="http://tempuri.org/IStatic/SaveCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Category>> SaveCategoriesAsync(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeTransactionReasons", ReplyAction="http://tempuri.org/IStatic/SaveTypeTransactionReasonsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> SaveTypeTransactionReasons(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeTransactionReasons", ReplyAction="http://tempuri.org/IStatic/SaveTypeTransactionReasonsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason>> SaveTypeTransactionReasonsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveNotifications", ReplyAction="http://tempuri.org/IStatic/SaveNotificationsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.Notification> SaveNotifications(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveNotifications", ReplyAction="http://tempuri.org/IStatic/SaveNotificationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Notification>> SaveNotificationsAsync(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeTransactions", ReplyAction="http://tempuri.org/IStatic/SaveTypeTransactionsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> SaveTypeTransactions(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeTransactions", ReplyAction="http://tempuri.org/IStatic/SaveTypeTransactionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction>> SaveTypeTransactionsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeFrequencies", ReplyAction="http://tempuri.org/IStatic/SaveTypeFrequenciesResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> SaveTypeFrequencies(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeFrequencies", ReplyAction="http://tempuri.org/IStatic/SaveTypeFrequenciesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency>> SaveTypeFrequenciesAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeIntervals", ReplyAction="http://tempuri.org/IStatic/SaveTypeIntervalsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> SaveTypeIntervals(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveTypeIntervals", ReplyAction="http://tempuri.org/IStatic/SaveTypeIntervalsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval>> SaveTypeIntervalsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveBudgetThresholds", ReplyAction="http://tempuri.org/IStatic/SaveBudgetThresholdsResponse")]
        System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> SaveBudgetThresholds(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatic/SaveBudgetThresholds", ReplyAction="http://tempuri.org/IStatic/SaveBudgetThresholdsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold>> SaveBudgetThresholdsAsync(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaticChannel : ConsoleApplication1.ServiceReference2.IStatic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaticClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference2.IStatic>, ConsoleApplication1.ServiceReference2.IStatic {
        
        public StaticClient() {
        }
        
        public StaticClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaticClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BMA.BusinessLogic.User AuthenticateUser(BMA.BusinessLogic.User user) {
            return base.Channel.AuthenticateUser(user);
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.User> AuthenticateUserAsync(BMA.BusinessLogic.User user) {
            return base.Channel.AuthenticateUserAsync(user);
        }
        
        public BMA.BusinessLogic.User RegisterUser(BMA.BusinessLogic.User user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.User> RegisterUserAsync(BMA.BusinessLogic.User user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public BMA.BusinessLogic.User ChangePassword(BMA.BusinessLogic.User user) {
            return base.Channel.ChangePassword(user);
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.User> ChangePasswordAsync(BMA.BusinessLogic.User user) {
            return base.Channel.ChangePasswordAsync(user);
        }
        
        public BMA.BusinessLogic.User ForgotPassword(BMA.BusinessLogic.User user) {
            return base.Channel.ForgotPassword(user);
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.User> ForgotPasswordAsync(BMA.BusinessLogic.User user) {
            return base.Channel.ForgotPasswordAsync(user);
        }
        
        public BMA.BusinessLogic.StaticTypeList GetAllStaticData() {
            return base.Channel.GetAllStaticData();
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.StaticTypeList> GetAllStaticDataAsync() {
            return base.Channel.GetAllStaticDataAsync();
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.Category> GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Category>> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> GetAllTypeTransactionReasons() {
            return base.Channel.GetAllTypeTransactionReasons();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason>> GetAllTypeTransactionReasonsAsync() {
            return base.Channel.GetAllTypeTransactionReasonsAsync();
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> GetAllTypeTransactions() {
            return base.Channel.GetAllTypeTransactions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction>> GetAllTypeTransactionsAsync() {
            return base.Channel.GetAllTypeTransactionsAsync();
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.Notification> GetUpcomingNotifications(System.DateTime clientTime) {
            return base.Channel.GetUpcomingNotifications(clientTime);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Notification>> GetUpcomingNotificationsAsync(System.DateTime clientTime) {
            return base.Channel.GetUpcomingNotificationsAsync(clientTime);
        }
        
        public BMA.BusinessLogic.StaticTypeList SyncStaticData(BMA.BusinessLogic.StaticTypeList staticData) {
            return base.Channel.SyncStaticData(staticData);
        }
        
        public System.Threading.Tasks.Task<BMA.BusinessLogic.StaticTypeList> SyncStaticDataAsync(BMA.BusinessLogic.StaticTypeList staticData) {
            return base.Channel.SyncStaticDataAsync(staticData);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.Category> SyncCategories(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories) {
            return base.Channel.SyncCategories(categories);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Category>> SyncCategoriesAsync(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories) {
            return base.Channel.SyncCategoriesAsync(categories);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> SyncTypeTransactionReasons(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason) {
            return base.Channel.SyncTypeTransactionReasons(typeTransactionReason);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason>> SyncTypeTransactionReasonsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason) {
            return base.Channel.SyncTypeTransactionReasonsAsync(typeTransactionReason);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.Notification> SyncNotifications(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications) {
            return base.Channel.SyncNotifications(notifications);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Notification>> SyncNotificationsAsync(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications) {
            return base.Channel.SyncNotificationsAsync(notifications);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> SyncTypeTransactions(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions) {
            return base.Channel.SyncTypeTransactions(typeTransactions);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction>> SyncTypeTransactionsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions) {
            return base.Channel.SyncTypeTransactionsAsync(typeTransactions);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> SyncTypeFrequencies(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies) {
            return base.Channel.SyncTypeFrequencies(typeFrequencies);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency>> SyncTypeFrequenciesAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies) {
            return base.Channel.SyncTypeFrequenciesAsync(typeFrequencies);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> SyncTypeIntervals(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval) {
            return base.Channel.SyncTypeIntervals(interval);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval>> SyncTypeIntervalsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval) {
            return base.Channel.SyncTypeIntervalsAsync(interval);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> SyncBudgetThresholds(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold) {
            return base.Channel.SyncBudgetThresholds(budgetThreshold);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold>> SyncBudgetThresholdsAsync(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold) {
            return base.Channel.SyncBudgetThresholdsAsync(budgetThreshold);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.Category> SaveCategories(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories) {
            return base.Channel.SaveCategories(categories);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Category>> SaveCategoriesAsync(System.Collections.Generic.List<BMA.BusinessLogic.Category> categories) {
            return base.Channel.SaveCategoriesAsync(categories);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> SaveTypeTransactionReasons(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason) {
            return base.Channel.SaveTypeTransactionReasons(typeTransactionReason);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason>> SaveTypeTransactionReasonsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransactionReason> typeTransactionReason) {
            return base.Channel.SaveTypeTransactionReasonsAsync(typeTransactionReason);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.Notification> SaveNotifications(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications) {
            return base.Channel.SaveNotifications(notifications);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.Notification>> SaveNotificationsAsync(System.Collections.Generic.List<BMA.BusinessLogic.Notification> notifications) {
            return base.Channel.SaveNotificationsAsync(notifications);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> SaveTypeTransactions(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions) {
            return base.Channel.SaveTypeTransactions(typeTransactions);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction>> SaveTypeTransactionsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeTransaction> typeTransactions) {
            return base.Channel.SaveTypeTransactionsAsync(typeTransactions);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> SaveTypeFrequencies(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies) {
            return base.Channel.SaveTypeFrequencies(typeFrequencies);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency>> SaveTypeFrequenciesAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeFrequency> typeFrequencies) {
            return base.Channel.SaveTypeFrequenciesAsync(typeFrequencies);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> SaveTypeIntervals(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval) {
            return base.Channel.SaveTypeIntervals(interval);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval>> SaveTypeIntervalsAsync(System.Collections.Generic.List<BMA.BusinessLogic.TypeInterval> interval) {
            return base.Channel.SaveTypeIntervalsAsync(interval);
        }
        
        public System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> SaveBudgetThresholds(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold) {
            return base.Channel.SaveBudgetThresholds(budgetThreshold);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold>> SaveBudgetThresholdsAsync(System.Collections.Generic.List<BMA.BusinessLogic.BudgetThreshold> budgetThreshold) {
            return base.Channel.SaveBudgetThresholdsAsync(budgetThreshold);
        }
    }
}
